# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: inventory_development
  username: root
  password: t3mp0r4l
  host: 127.0.0.1
  port: 3306
 
test:
  adapter: mysql2
  encoding: utf8
  database: inventory_test
  username: root
  password: t3mp0r4l
  host: 127.0.0.1
  port: 3306
 
production:
  adapter: mysql2
  encoding: utf8
  database: inventory_production 
  username: root
  password: t3mp0r4l
  host: 127.0.0.1
  port: 3306
